attr_fn_like_width = 100
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 100
color = "Always"
combine_control_expr = false
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_layout = "Vertical"
imports_granularity = "Crate"
reorder_imports = true
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 100
unstable_features = true
wrap_comments = true
